language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
before_install:
# 解密 RSA 私钥并设置为本机 ssh 私钥
- openssl aes-256-cbc -K $encrypted_b22e95f4e500_key -iv $encrypted_b22e95f4e500_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "asd2766"
- git config --global user.email "270092797@qq.com"
- npm global add hexo-cli
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh
- export TZ='Asia/Wenzhou'
install:
- npm install
script:
- hexo clean
- hexo d -g
after_success:
- hexo deploy
after_script:
# 先 clone 再 commit，避免直接 force commit
# 不然整个 branch 就总是只有一个 commit，不好看
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config user.name "asd2766"
- git config user.email "270092797@qq.com"
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
# 同时 push 一份到自己的服务器上
- git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/asd2766/blogsBackup.git
notifications:
  email:
  - 270092797@qq.com
  on_success: change
  on_failure: always
dd:
- openssl aes-256-cbc -K $encrypted_1d864db4769b_key -iv $encrypted_1d864db4769b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
